# Generated by Django 3.2.8 on 2021-10-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_slot', models.IntegerField(default=1)),
                ('booking_time', models.DateField()),
                ('booking_owner',  models.IntegerField(default=1)),
            ],
        ),
    ]
