# Generated by Django 3.2.8 on 2021-10-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_slott_slott_nr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user_email',
        ),
    ]
