# Generated by Django 3.2.8 on 2021-10-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_rename_email_user_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_owner',
            field=models.IntegerField(default=1),
        ),
    ]
